wamv: #namespace
    task_and_robot_environment_name: 'WamvNavTwoSetsBuoys-v0'
    ros_ws_abspath: "/home/user/simulation_ws"
    #qlearn parameters
    n_observations: 9
    n_actions: 4 # Number of actions used by algorithm and task
    episodes_training: 40
    episodes_running: 10
    n_win_ticks: 80 # If the mean of rewards is bigger than this and have passed min_episodes, the task is considered finished
    min_episodes: 10
    gamma: 1.0 # future rewards value 0 none 1 a lot
    epsilon: 1.0 # exploration, 0 none 1 a lot
    epsilon_decay: 0.995 # how we reduse the exploration
    epsilon_min: 0.01 # minimum value that epsilon can have
    alpha: 0.01 # Learning Rate
    alpha_decay: 0.01
    batch_size: 64 # maximum size of the batches sampled from memory
    #max_env_steps: None
    monitor: True
    quiet: False