husarion: #namespace

    task_and_robot_environment_name: 'HusarionGetToPosTurtleBotPlayGround-v0'
    ros_ws_abspath: "/home/user/simulation_ws"
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 500
    nsteps: 1000
    running_step: 0.04 # amount of time the control will be executed